### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by itsashis4u** [braz/modelling-with-mongoose#1]
Error installing dep `sleep`

```
itsashis4u@ashish-inspiron:~$ npm install -g braz/modelling-with-mongoose

> sleep@1.1.8 install /home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/sleep
> node build.js || nodejs build.js

child_process: customFds option is deprecated, use stdio instead.
gyp: braz/modelling-with-mongoose not found (cwd: /home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/sleep) while trying to load braz/modelling-with-mongoose
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.2.0-86-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--global" "braz/modelling-with-mongoose"
gyp ERR! cwd /home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/sleep
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
[sleep]: Error: Failed to execute 'node-gyp rebuild --global braz/modelling-with-mongoose' (1)
sh: 1: nodejs: not found
|
> kerberos@0.0.11 install /home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: Leaving directory `/home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'

> bson@0.2.22 install /home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory `/home/itsashis4u/.npm-packages/lib/node_modules/modelling-with-mongoose/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
npm ERR! Linux 3.2.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "braz/modelling-with-mongoose"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! sleep@1.1.8 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sleep@1.1.8 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/itsashis4u/npm-debug.log

```

**Comment by hexicle** [comment]
I have the same error 4 months later. Code hasn't been updated for 2 years.
